services:
  mongodb:
    image: mongo:8
    container_name: openfox-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  openfox:
    build: .
    image: openfox:latest
    container_name: openfox
    restart: always
    ports:
      - "7777:7777"

volumes:
  mongo_data:
