/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppPageScaffold: typeof import('./src/components/AppPageScaffold.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    ChatToolCallsCard: typeof import('./src/components/ChatToolCallsCard.vue')['default']
    ChatToolOutputTags: typeof import('./src/components/ChatToolOutputTags.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UBreadcrumb: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UChatMessages: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.vue')['default']
    UChatPrompt: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.vue')['default']
    UChatPromptSubmit: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.vue')['default']
    UChatTool: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/ChatTool.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UCollapsible: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue')['default']
    UDashboardGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UDashboardSidebarCollapse: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue')['default']
    UDashboardSidebarToggle: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UForm: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPopover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USeparator: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTable: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.6.1_@tiptap+extensions@3.22.3_@tiptap+core@3.22.3_@tiptap+pm@3.22.3__@tiptap_fafa2c8fd8069605b89c294f69939ef7/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
