/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '//': RouteRecordInfo<
      '//',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//config': RouteRecordInfo<
      '//config',
      '/config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//docs': RouteRecordInfo<
      '//docs',
      '/docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//evals': RouteRecordInfo<
      '//evals',
      '/evals',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//knowledge': RouteRecordInfo<
      '//knowledge',
      '/knowledge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//memory': RouteRecordInfo<
      '//memory',
      '/memory',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//scheduler': RouteRecordInfo<
      '//scheduler',
      '/scheduler',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//sessions': RouteRecordInfo<
      '//sessions',
      '/sessions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//skills': RouteRecordInfo<
      '//skills',
      '/skills',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//traces': RouteRecordInfo<
      '//traces',
      '/traces',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//usage': RouteRecordInfo<
      '//usage',
      '/usage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index/index.vue': {
      routes:
        | '//'
      views:
        | never
    }
    'src/pages/index/config.vue': {
      routes:
        | '//config'
      views:
        | never
    }
    'src/pages/index/docs.vue': {
      routes:
        | '//docs'
      views:
        | never
    }
    'src/pages/index/evals.vue': {
      routes:
        | '//evals'
      views:
        | never
    }
    'src/pages/index/knowledge.vue': {
      routes:
        | '//knowledge'
      views:
        | never
    }
    'src/pages/index/memory.vue': {
      routes:
        | '//memory'
      views:
        | never
    }
    'src/pages/index/scheduler.vue': {
      routes:
        | '//scheduler'
      views:
        | never
    }
    'src/pages/index/sessions.vue': {
      routes:
        | '//sessions'
      views:
        | never
    }
    'src/pages/index/skills.vue': {
      routes:
        | '//skills'
      views:
        | never
    }
    'src/pages/index/traces.vue': {
      routes:
        | '//traces'
      views:
        | never
    }
    'src/pages/index/usage.vue': {
      routes:
        | '//usage'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
